version: '2.4'

networks:
  proxy:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/24"
          gateway: "10.0.0.1"
          ip_range: "10.0.0.0/24"

services:

  traefik:
    image: traefik:latest
    container_name: "traefik"
    domainname: kk7mnz.com
    hostname: traefik_container
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # logging
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/traefik.log"
      - "--accesslog.bufferingsize=100"
      # create entrypoints
      - "--entrypoints.www.address=:80"
      - "--entrypoints.traefik.address=:8080"
      # xlxd
      - "--entrypoints.xlxd-repnet.address=:8080/udp"
      - "--entrypoints.xlxd-xlxcore.address=:10001/udp"
      - "--entrypoints.xlxd-ysf.address=:42000/udp"
      - "--entrypoints.xlxd-dextra.address=:30001/udp"
      - "--entrypoints.xlxd-dplus.address=:20001/udp"
      - "--entrypoints.xlxd-dcs.address=:30051/udp"
      - "--entrypoints.xlxd-dmr.address=:8880/udp"
      - "--entrypoints.xlxd-mmdvm.address=:62030/udp"
      - "--entrypoints.xlxd-icom-terminal-1.address=:12345/udp"
      - "--entrypoints.xlxd-icom-terminal-2.address=:12346/udp"
      - "--entrypoints.xlxd-icom-dv.address=:40000/udp"
      - "--entrypoints.xlxd-yaesu-imrs.address=:21220/udp"
    ports:
      # The HTTP port
      - "0.0.0.0:80:80/tcp"
      # The Web UI (enabled by --api.insecure=true)
      - "0.0.0.0:8080:8080/tcp"
    networks:
      proxy:
        ipv4_address: "10.0.0.2"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/traefik/traefik.log:/var/log/traefik.log
      #- /opt/traefik/traefik.toml:/traefik.toml
    dns:
      - 1.1.1.1
    dns_search: kk7mnz.com
    restart: unless-stopped

  xlxd:
    image: mfiscus/xlxd:latest
    container_name: xlxd
    domainname: kk7mnz.com
    hostname: xlxd_container
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=docker_proxy"
      - "traefik.frontend=xlxd-frontend"
      - "traefik.frontend.rule=HostRegexp:xlx847.kk7mnz.com,{catchall:.*}"
      # HTTP routers
      - "traefik.http.routers.xlxd-frontend.rule=Host(`xlx847.kk7mnz.com`)"
      - "traefik.http.routers.xlxd-frontend.entrypoints=www"
      - "traefik.http.services.xlxd-frontend.loadbalancer.server.port=8470"
      # UDP routers
      # repnet
      - "traefik.udp.routers.xlxd-repnet.entrypoints=xlxd-repnet"
      - "traefik.udp.routers.xlxd-repnet.service=xlxd-repnet"
      - "traefik.udp.services.xlxd-repnet.loadbalancer.server.port=8080"
      # xlxcore
      - "traefik.udp.routers.xlxd-xlxcore.entrypoints=xlxd-xlxcore"
      - "traefik.udp.routers.xlxd-xlxcore.service=xlxd-xlxcore"
      - "traefik.udp.services.xlxd-xlxcore.loadbalancer.server.port=10001"
      # xlxd-ysf
      - "traefik.udp.routers.xlxd-ysf.entrypoints=xlxd-ysf"
      - "traefik.udp.routers.xlxd-ysf.service=xlxd-ysf"
      - "traefik.udp.services.xlxd-ysf.loadbalancer.server.port=42000"
      # xlxd-dextra
      - "traefik.udp.routers.xlxd-dextra.entrypoints=xlxd-dextra"
      - "traefik.udp.routers.xlxd-dextra.service=xlxd-dextra"
      - "traefik.udp.services.xlxd-dextra.loadbalancer.server.port=30001"
      # xlxd-dplus
      - "traefik.udp.routers.xlxd-dplus.entrypoints=xlxd-dplus"
      - "traefik.udp.routers.xlxd-dplus.service=xlxd-dplus"
      - "traefik.udp.services.xlxd-dplus.loadbalancer.server.port=20001"
      # dcs
      - "traefik.udp.routers.xlxd-dcs.entrypoints=xlxd-dcs"
      - "traefik.udp.routers.xlxd-dcs.service=xlxd-dcs"
      - "traefik.udp.services.xlxd-dcs.loadbalancer.server.port=30051"
      # dmr
      - "traefik.udp.routers.xlxd-dmr.entrypoints=xlxd-dmr"
      - "traefik.udp.routers.xlxd-dmr.service=xlxd-dmr"
      - "traefik.udp.services.xlxd-dmr.loadbalancer.server.port=8880"
      # mmdvm
      - "traefik.udp.routers.xlxd-mmdvm.entrypoints=xlxd-mmdvm"
      - "traefik.udp.routers.xlxd-mmdvm.service=xlxd-mmdvm"
      - "traefik.udp.services.xlxd-mmdvm.loadbalancer.server.port=62030"
      # icom-terminal-1
      - "traefik.udp.routers.xlxd-icom-terminal-1.entrypoints=xlxd-icom-terminal-1"
      - "traefik.udp.routers.xlxd-icom-terminal-1.service=xlxd-icom-terminal-1"
      - "traefik.udp.services.xlxd-icom-terminal-1.loadbalancer.server.port=12345"
      # icom-terminal-2
      - "traefik.udp.routers.xlxd-icom-terminal-2.entrypoints=xlxd-icom-terminal-2"
      - "traefik.udp.routers.xlxd-icom-terminal-2.service=xlxd-icom-terminal-2"
      - "traefik.udp.services.xlxd-icom-terminal-2.loadbalancer.server.port=12346"
      # icom-dv
      - "traefik.udp.routers.xlxd-icom-dv.entrypoints=xlxd-icom-dv"
      - "traefik.udp.routers.xlxd-icom-dv.service=xlxd-icom-dv"
      - "traefik.udp.services.xlxd-icom-dv.loadbalancer.server.port=40000"
      # yaesu-imrs
      - "traefik.udp.routers.xlxd-yaesu-imrs.entrypoints=xlxd-yaesu-imrs"
      - "traefik.udp.routers.xlxd-yaesu-imrs.service=xlxd-yaesu-imrs"
      - "traefik.udp.services.xlxd-yaesu-imrs.loadbalancer.server.port=21220"
    environment:
      CALLSIGN: 'KK7MNZ'
      EMAIL: 'matt@kk7mnz.com'
      # URL for dashboard
      URL: 'xlx847.kk7mnz.com'
      # Port to run dashboard on
      PORT: '8470'
      XRFNUM: 'XLX847'
      COUNTRY: 'United States'
      # Make your ysf reflector stand out in the list
      DESCRIPTION: 'Chandler Ham Radio Club'
      # Number of modules to run (default: 10, max: 26)
      MODULES: '4'
      # Support for labeling first 4 modules
      MODULEA: 'Main'
      MODULEB: 'TBD'
      MODULEC: 'TBD'
      MODULED: 'TBD'
      # Enable ysf auto linking (disable: 0, enable: 1)
      YSF_AUTOLINK_ENABLE: '1'
      # Define default module to auto link to
      YSF_AUTOLINK_MODULE: 'A'
      # I read somewhere that it was important to define this so I built in support. Not sure what it is for yet.
      YSF_DEFAULT_NODE_RX_FREQ: '438000000'
      YSF_DEFAULT_NODE_TX_FREQ: '438000000'
    networks:
      proxy:
        ipv4_address: "10.0.0.3"
    volumes:
      # volume for storing custom configuration files
      - /opt/xlxd:/config
    privileged: true
    devices:
      # grant access to AMBE USB DV vocodor (tested with ThumbDV)
      - /dev/usb:/dev/usb
    dns:
      - 1.1.1.1
    dns_search: kk7mnz.com
    restart: unless-stopped
    