version: '2.4'

networks:
  proxy:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/24"
          gateway: "10.0.0.1"
          ip_range: "10.0.0.0/24"

services:

  traefik:
    image: traefik:latest
    container_name: "traefik"
    domainname: kk7mnz.com
    hostname: traefik_container
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # logging
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/traefik.log"
      - "--accesslog.bufferingsize=100"
      # create entrypoints
      - "--entrypoints.www.address=:80"
      - "--entrypoints.traefik.address=:8080"
      # xlxd
      - "--entrypoints.xlxd-repnet.address=:8080/udp"
      - "--entrypoints.xlxd-xlxcore.address=:10001/udp"
      - "--entrypoints.xlxd-ysf.address=:42000/udp"
      - "--entrypoints.xlxd-dextra.address=:30001/udp"
      - "--entrypoints.xlxd-dplus.address=:20001/udp"
      - "--entrypoints.xlxd-dcs.address=:30051/udp"
      - "--entrypoints.xlxd-dmr.address=:8880/udp"
      - "--entrypoints.xlxd-mmdvm.address=:62030/udp"
      - "--entrypoints.xlxd-icom-terminal-1.address=:12345/udp"
      - "--entrypoints.xlxd-icom-terminal-2.address=:12346/udp"
      - "--entrypoints.xlxd-icom-dv.address=:40000/udp"
      - "--entrypoints.xlxd-yaesu-imrs.address=:21220/udp"
    ports:
      # The HTTP port
      - "0.0.0.0:80:80/tcp"
      # The Web UI (enabled by --api.insecure=true)
      - "0.0.0.0:8080:8080/tcp"
    networks:
      proxy:
        ipv4_address: "10.0.0.2"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/traefik/traefik.log:/var/log/traefik.log
      #- /opt/traefik/traefik.toml:/traefik.toml
    dns:
      - 1.1.1.1
    dns_search: kk7mnz.com
    restart: unless-stopped

  xlxd:
    image: mfiscus/xlxd:latest
    container_name: xlxd
    domainname: kk7mnz.com
    hostname: xlxd_container
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=docker_proxy"
      - "traefik.frontend=xlxd-frontend"
      - "traefik.frontend.rule=HostRegexp:xlx847.kk7mnz.com,{catchall:.*}"
      - "traefik.http.routers.xlxd-frontend.rule=Host(`xlx847.kk7mnz.com`)"
      - "traefik.http.routers.xlxd-frontend.entrypoints=www"
      - "traefik.http.services.xlxd-frontend.loadbalancer.server.port=8470"
    environment:
      CALLSIGN: 'KK7MNZ'
      EMAIL: 'matt@kk7mnz.com'
      # URL for dashboard
      URL: 'xlx847.kk7mnz.com'
      # Port to run dashboard on
      PORT: '8470'
      XRFNUM: 'XLX847'
      COUNTRY: 'United States'
      # Make your ysf reflector stand out in the list
      DESCRIPTION: 'Chandler Ham Radio Club'
      # Number of modules to run (default: 10, max: 26)
      MODULES: '4'
      # Support for labeling first 4 modules
      MODULEA: 'Main'
      MODULEB: 'TBD'
      MODULEC: 'TBD'
      MODULED: 'TBD'
      # Enable ysf auto linking (disable: 0, enable: 1)
      YSF_AUTOLINK_ENABLE: '1'
      # Define default module to auto link to
      YSF_AUTOLINK_MODULE: 'A'
      # I read somewhere that it was important to define this so I built in support. Not sure what it is for yet.
      YSF_DEFAULT_NODE_RX_FREQ: '438000000'
      YSF_DEFAULT_NODE_TX_FREQ: '438000000'
    networks:
      proxy:
        ipv4_address: "10.0.0.3"
    volumes:
      # volume for storing custom configuration files
      - /opt/xlxd:/config
    privileged: true
    devices:
      # grant access to AMBE USB DV vocodor (tested with ThumbDV)
      - /dev/usb:/dev/usb
    dns:
      - 1.1.1.1
    dns_search: kk7mnz.com
    restart: unless-stopped
    