version: '3.8'

services:
  xlxd:
    image: mfiscus/xlxd:latest
    container_name: xlxd
    hostname: xlxd_container
    environment:
      # only set CALLHOME to true once your are certain your configuration is correct
      # make sure you backup your callinghome.php file (which should be located on the docker host in /opt/xlxd/) 
      CALLHOME: 'false' 
      CALLSIGN: 'LY3PH'
      EMAIL: 'ly3ph@qsl.lt'
      URL: 'xlx.qsl.lt'
      PORT: '80'
      XLXNUM: 'XLX642'
      AMBED: 'ip_of_ambed'
      COUNTRY: 'Lithuania'
      DESCRIPTION: 'Lithuania XLX DMR-YSF-DStar Reflector'
      # Define how many modules you require
      MODULES: '1'
      # Name your modules however you like (container only supports naming first 4)
      MODULEA: 'Global'
      MODULEB: 'TBD'
      MODULEC: 'TBD'
      MODULED: 'TBD'
      TZ: 'EET'
    volumes:
      # local directory where state and config files (including callinghome.php) will be saved
      - /opt/xlxd:/config
    restart: unless-stopped
