version: '2.4'

networks:
  proxy:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/24"
          gateway: "10.0.0.1"
          ip_range: "10.0.0.0/24"

services:

  traefik:
    image: traefik:latest
    container_name: "traefik"
    domainname: fisc.us
    hostname: traefik_container
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # logging
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/traefik.log"
      - "--accesslog.bufferingsize=100"
      # create entrypoints
      - "--entrypoints.www.address=:80"
      - "--entrypoints.traefik.address=:8080"
      # xlxd
      - "--entrypoints.xlxd-http.address=:8470"
      - "--entrypoints.xlxd-repnet.address=:8080/udp"
      - "--entrypoints.xlxd-xlxcore.address=:10001/udp"
      - "--entrypoints.xlxd-ysf.address=:42000/udp"
      - "--entrypoints.xlxd-dextra.address=:30001/udp"
      - "--entrypoints.xlxd-dplus.address=:20001/udp"
      - "--entrypoints.xlxd-dcs.address=:30051/udp"
      - "--entrypoints.xlxd-dmr.address=:8880/udp"
      - "--entrypoints.xlxd-mmdvm.address=:62030/udp"
      - "--entrypoints.xlxd-icom-terminal-1.address=:12345/udp"
      - "--entrypoints.xlxd-icom-terminal-2.address=:12346/udp"
      - "--entrypoints.xlxd-icom-dv.address=:40000/udp"
      - "--entrypoints.xlxd-yaesu-imrs.address=:21110/udp"
    ports:
      # The HTTP port
      - "0.0.0.0:80:80/tcp"
      # The Web UI (enabled by --api.insecure=true)
      - "0.0.0.0:8080:8080/tcp"
      # xlxd ports
      - 8470:8470/tcp
      - 8080:8080/udp
      - 10001:10001/udp
      - 10002:10002/udp
      - 42000:42000/udp
      - 30001:30001/udp
      - 20001:20001/udp
      - 30051:30051/udp
      - 8880:8880/udp
      - 62030:62030/udp
      - 12345:12345/udp
      - 12346:12346/udp
      - 40000:40000/udp
      - 21110:21110/udp
    networks:
      - proxy
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
    dns:
      - 1.1.1.1
    dns_search: kk7mnz.com
    restart: unless-stopped

  xlxd:
    image: mfiscus/xlxd:latest
    container_name: xlxd
    domainname: kk7mnz.com
    hostname: xlxd_container
    depends_on:
      - traefik
    labels:
      - "traefik.xlxd-http.rule=HostRegexp:xlx847.kk7mnz.com,{catchall:.*}"
      - "traefik.xlxd-http.priority=1"
      - "traefik.xlxd-http=xlxd-xlxd-http"
      #- "traefik.port=80"
      - "traefik.docker.network=docker_proxy"
      # Explicitly tell Traefik to expose this container
      - "traefik.enable=true"
      # The domain the service will respond to
      - "traefik.http.routers.xlxd-http.rule=Host(`xlx847.kk7mnz.com`)"
      # Allow request only from the predefined entry point named "www"
      - "traefik.http.routers.xlxd-http.entrypoints=xlxd-http"
      # Specify port
      - "traefik.http.services.xlxd-http.loadbalancer.server.port=8470"
      # test alternate http port
      - "traefik.http.routers.xlxd-http.service=xlxd-http"
      # UDP routers
      # repnet
      - "traefik.udp.routers.xlxd-repnet.entrypoints=xlxd-repnet"
      - "traefik.udp.routers.xlxd-repnet.service=xlxd-repnet"
      - "traefik.udp.services.xlxd-repnet.loadbalancer.server.port=8080"
      # xlxcore
      - "traefik.udp.routers.xlxd-xlxcore.entrypoints=xlxd-xlxcore"
      - "traefik.udp.routers.xlxd-xlxcore.service=xlxd-xlxcore"
      - "traefik.udp.services.xlxd-xlxcore.loadbalancer.server.port=10001"
      # xlxd-ysf
      - "traefik.udp.routers.xlxd-ysf.entrypoints=xlxd-ysf"
      - "traefik.udp.routers.xlxd-ysf.service=xlxd-ysf"
      - "traefik.udp.services.xlxd-ysf.loadbalancer.server.port=42000"
      # xlxd-dextra
      - "traefik.udp.routers.xlxd-dextra.entrypoints=xlxd-dextra"
      - "traefik.udp.routers.xlxd-dextra.service=xlxd-dextra"
      - "traefik.udp.services.xlxd-dextra.loadbalancer.server.port=30001"
      # xlxd-dplus
      - "traefik.udp.routers.xlxd-dplus.entrypoints=xlxd-dplus"
      - "traefik.udp.routers.xlxd-dplus.service=xlxd-dplus"
      - "traefik.udp.services.xlxd-dplus.loadbalancer.server.port=20001"
      # dcs
      - "traefik.udp.routers.xlxd-dcs.entrypoints=xlxd-dcs"
      - "traefik.udp.routers.xlxd-dcs.service=xlxd-dcs"
      - "traefik.udp.services.xlxd-dcs.loadbalancer.server.port=30051"
      # dmr
      - "traefik.udp.routers.xlxd-dmr.entrypoints=xlxd-dmr"
      - "traefik.udp.routers.xlxd-dmr.service=xlxd-dmr"
      - "traefik.udp.services.xlxd-dmr.loadbalancer.server.port=8880"
      # mmdvm
      - "traefik.udp.routers.xlxd-mmdvm.entrypoints=xlxd-mmdvm"
      - "traefik.udp.routers.xlxd-mmdvm.service=xlxd-mmdvm"
      - "traefik.udp.services.xlxd-mmdvm.loadbalancer.server.port=62030"
      # icom-terminal-1
      - "traefik.udp.routers.xlxd-icom-terminal-1.entrypoints=xlxd-icom-terminal-1"
      - "traefik.udp.routers.xlxd-icom-terminal-1.service=xlxd-icom-terminal-1"
      - "traefik.udp.services.xlxd-icom-terminal-1.loadbalancer.server.port=12345"
      # icom-terminal-2
      - "traefik.udp.routers.xlxd-icom-terminal-2.entrypoints=xlxd-icom-terminal-2"
      - "traefik.udp.routers.xlxd-icom-terminal-2.service=xlxd-icom-terminal-2"
      - "traefik.udp.services.xlxd-icom-terminal-2.loadbalancer.server.port=12346"
      # icom-dv
      - "traefik.udp.routers.xlxd-icom-dv.entrypoints=xlxd-icom-dv"
      - "traefik.udp.routers.xlxd-icom-dv.service=xlxd-icom-dv"
      - "traefik.udp.services.xlxd-icom-dv.loadbalancer.server.port=40000"
      # yaesu-imrs
      - "traefik.udp.routers.xlxd-yaesu-imrs.entrypoints=xlxd-yaesu-imrs"
      - "traefik.udp.routers.xlxd-yaesu-imrs.service=xlxd-yaesu-imrs"
      - "traefik.udp.services.xlxd-yaesu-imrs.loadbalancer.server.port=21110"
    environment:
      CALLSIGN: 'KK7MNZ'
      EMAIL: 'you@email.com'
      URL: 'your.dashboard.url'
      PORT: '80'
      XRFNUM: 'XLX000'
      COUNTRY: 'United States'
      DESCRIPTION: 'Your Reflector Description'
      MODULES: '4'
      MODULEA: 'Main'
      MODULEB: 'TBD'
      MODULEC: 'TBD'
      MODULED: 'TBD'
      YSF_AUTOLINK_ENABLE: '1'
      YSF_AUTOLINK_MODULE: 'A'
      YSF_DEFAULT_NODE_RX_FREQ: '438000000'
      YSF_DEFAULT_NODE_TX_FREQ: '438000000'
    networks:
      - proxy
    volumes:
      - /opt/xlxd:/config
    device_cgroup_rules:
      - 'c 188:* rmw'
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    dns:
      - 1.1.1.1
    dns_search: kk7mnz.com
    restart: unless-stopped
    