version: '2.4'

networks:
  proxy:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/24"
          gateway: "10.0.0.1"
          ip_range: "10.0.0.0/24"

services:

  traefik:
    image: traefik:latest
    container_name: "traefik"
    domainname: kk7mnz.com
    hostname: traefik_container
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # logging
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/traefik.log"
      - "--accesslog.bufferingsize=100"
      # create entrypoints
      - "--entrypoints.www.address=:80"
      - "--entrypoints.traefik.address=:8080"
      # xlxd
      - "--entrypoints.xlxd-repnet.address=:8080/udp"
      - "--entrypoints.xlxd-xlxcore.address=:10001/udp"
      - "--entrypoints.xlxd-ysf.address=:42000/udp"
      - "--entrypoints.xlxd-dextra.address=:30001/udp"
      - "--entrypoints.xlxd-dplus.address=:20001/udp"
      - "--entrypoints.xlxd-dcs.address=:30051/udp"
      - "--entrypoints.xlxd-dmr.address=:8880/udp"
      - "--entrypoints.xlxd-mmdvm.address=:62030/udp"
      - "--entrypoints.xlxd-icom-terminal-1.address=:12345/udp"
      - "--entrypoints.xlxd-icom-terminal-2.address=:12346/udp"
      - "--entrypoints.xlxd-icom-dv.address=:40000/udp"
      - "--entrypoints.xlxd-yaesu-imrs.address=:21220/udp"
      - "--entrypoints.xlxd-ambe.address=:10100/udp"
      - "--entrypoints.xlxd-ambe-transcode-1.address=:10101/udp"
      - "--entrypoints.xlxd-ambe-transcode-2.address=:10102/udp"
      # - "--entrypoints.xlxd-ambe-transcode-3.address=:10103/udp"
      # - "--entrypoints.xlxd-ambe-transcode-4.address=:10104/udp"
      # - "--entrypoints.xlxd-ambe-transcode-5.address=:10105/udp"
      # - "--entrypoints.xlxd-ambe-transcode-6.address=:10106/udp"
      # - "--entrypoints.xlxd-ambe-transcode-7.address=:10107/udp"
      # - "--entrypoints.xlxd-ambe-transcode-8.address=:10108/udp"
      # - "--entrypoints.xlxd-ambe-transcode-9.address=:10109/udp"
      # - "--entrypoints.xlxd-ambe-transcode-10.address=:10110/udp"
      # - "--entrypoints.xlxd-ambe-transcode-11.address=:10111/udp"
      # - "--entrypoints.xlxd-ambe-transcode-12.address=:10112/udp"
      # - "--entrypoints.xlxd-ambe-transcode-13.address=:10113/udp"
      # - "--entrypoints.xlxd-ambe-transcode-14.address=:10114/udp"
      # - "--entrypoints.xlxd-ambe-transcode-15.address=:10115/udp"
      # - "--entrypoints.xlxd-ambe-transcode-16.address=:10116/udp"
      # - "--entrypoints.xlxd-ambe-transcode-17.address=:10117/udp"
      # - "--entrypoints.xlxd-ambe-transcode-18.address=:10118/udp"
      # - "--entrypoints.xlxd-ambe-transcode-19.address=:10119/udp"
      # - "--entrypoints.xlxd-ambe-transcode-20.address=:10120/udp"
      # - "--entrypoints.xlxd-ambe-transcode-21.address=:10121/udp"
      # - "--entrypoints.xlxd-ambe-transcode-22.address=:10122/udp"
      # - "--entrypoints.xlxd-ambe-transcode-23.address=:10123/udp"
      # - "--entrypoints.xlxd-ambe-transcode-24.address=:10124/udp"
      # - "--entrypoints.xlxd-ambe-transcode-25.address=:10125/udp"
      # - "--entrypoints.xlxd-ambe-transcode-26.address=:10126/udp"
      # - "--entrypoints.xlxd-ambe-transcode-27.address=:10127/udp"
      # - "--entrypoints.xlxd-ambe-transcode-28.address=:10128/udp"
      # - "--entrypoints.xlxd-ambe-transcode-29.address=:10129/udp"
      # - "--entrypoints.xlxd-ambe-transcode-30.address=:10130/udp"
      # - "--entrypoints.xlxd-ambe-transcode-31.address=:10131/udp"
      # - "--entrypoints.xlxd-ambe-transcode-32.address=:10132/udp"
      # - "--entrypoints.xlxd-ambe-transcode-33.address=:10133/udp"
      # - "--entrypoints.xlxd-ambe-transcode-34.address=:10134/udp"
      # - "--entrypoints.xlxd-ambe-transcode-35.address=:10135/udp"
      # - "--entrypoints.xlxd-ambe-transcode-36.address=:10136/udp"
      # - "--entrypoints.xlxd-ambe-transcode-37.address=:10137/udp"
      # - "--entrypoints.xlxd-ambe-transcode-38.address=:10138/udp"
      # - "--entrypoints.xlxd-ambe-transcode-39.address=:10139/udp"
      # - "--entrypoints.xlxd-ambe-transcode-40.address=:10140/udp"
      # - "--entrypoints.xlxd-ambe-transcode-41.address=:10141/udp"
      # - "--entrypoints.xlxd-ambe-transcode-42.address=:10142/udp"
      # - "--entrypoints.xlxd-ambe-transcode-43.address=:10143/udp"
      # - "--entrypoints.xlxd-ambe-transcode-44.address=:10144/udp"
      # - "--entrypoints.xlxd-ambe-transcode-45.address=:10145/udp"
      # - "--entrypoints.xlxd-ambe-transcode-46.address=:10146/udp"
      # - "--entrypoints.xlxd-ambe-transcode-47.address=:10147/udp"
      # - "--entrypoints.xlxd-ambe-transcode-48.address=:10148/udp"
      # - "--entrypoints.xlxd-ambe-transcode-49.address=:10149/udp"
      # - "--entrypoints.xlxd-ambe-transcode-50.address=:10150/udp"
      # - "--entrypoints.xlxd-ambe-transcode-51.address=:10151/udp"
      # - "--entrypoints.xlxd-ambe-transcode-52.address=:10152/udp"
      # - "--entrypoints.xlxd-ambe-transcode-53.address=:10153/udp"
      # - "--entrypoints.xlxd-ambe-transcode-54.address=:10154/udp"
      # - "--entrypoints.xlxd-ambe-transcode-55.address=:10155/udp"
      # - "--entrypoints.xlxd-ambe-transcode-56.address=:10156/udp"
      # - "--entrypoints.xlxd-ambe-transcode-57.address=:10157/udp"
      # - "--entrypoints.xlxd-ambe-transcode-58.address=:10158/udp"
      # - "--entrypoints.xlxd-ambe-transcode-59.address=:10159/udp"
      # - "--entrypoints.xlxd-ambe-transcode-60.address=:10160/udp"
      # - "--entrypoints.xlxd-ambe-transcode-61.address=:10161/udp"
      # - "--entrypoints.xlxd-ambe-transcode-62.address=:10162/udp"
      # - "--entrypoints.xlxd-ambe-transcode-63.address=:10163/udp"
      # - "--entrypoints.xlxd-ambe-transcode-64.address=:10164/udp"
      # - "--entrypoints.xlxd-ambe-transcode-65.address=:10165/udp"
      # - "--entrypoints.xlxd-ambe-transcode-66.address=:10166/udp"
      # - "--entrypoints.xlxd-ambe-transcode-67.address=:10167/udp"
      # - "--entrypoints.xlxd-ambe-transcode-68.address=:10168/udp"
      # - "--entrypoints.xlxd-ambe-transcode-69.address=:10169/udp"
      # - "--entrypoints.xlxd-ambe-transcode-70.address=:10170/udp"
      # - "--entrypoints.xlxd-ambe-transcode-71.address=:10171/udp"
      # - "--entrypoints.xlxd-ambe-transcode-72.address=:10172/udp"
      # - "--entrypoints.xlxd-ambe-transcode-73.address=:10173/udp"
      # - "--entrypoints.xlxd-ambe-transcode-74.address=:10174/udp"
      # - "--entrypoints.xlxd-ambe-transcode-75.address=:10175/udp"
      # - "--entrypoints.xlxd-ambe-transcode-76.address=:10176/udp"
      # - "--entrypoints.xlxd-ambe-transcode-77.address=:10177/udp"
      # - "--entrypoints.xlxd-ambe-transcode-78.address=:10178/udp"
      # - "--entrypoints.xlxd-ambe-transcode-79.address=:10179/udp"
      # - "--entrypoints.xlxd-ambe-transcode-80.address=:10180/udp"
      # - "--entrypoints.xlxd-ambe-transcode-81.address=:10181/udp"
      # - "--entrypoints.xlxd-ambe-transcode-82.address=:10182/udp"
      # - "--entrypoints.xlxd-ambe-transcode-83.address=:10183/udp"
      # - "--entrypoints.xlxd-ambe-transcode-84.address=:10184/udp"
      # - "--entrypoints.xlxd-ambe-transcode-85.address=:10185/udp"
      # - "--entrypoints.xlxd-ambe-transcode-86.address=:10186/udp"
      # - "--entrypoints.xlxd-ambe-transcode-87.address=:10187/udp"
      # - "--entrypoints.xlxd-ambe-transcode-88.address=:10188/udp"
      # - "--entrypoints.xlxd-ambe-transcode-89.address=:10189/udp"
      # - "--entrypoints.xlxd-ambe-transcode-90.address=:10190/udp"
      # - "--entrypoints.xlxd-ambe-transcode-91.address=:10191/udp"
      # - "--entrypoints.xlxd-ambe-transcode-92.address=:10192/udp"
      # - "--entrypoints.xlxd-ambe-transcode-93.address=:10193/udp"
      # - "--entrypoints.xlxd-ambe-transcode-94.address=:10194/udp"
      # - "--entrypoints.xlxd-ambe-transcode-95.address=:10195/udp"
      # - "--entrypoints.xlxd-ambe-transcode-96.address=:10196/udp"
      # - "--entrypoints.xlxd-ambe-transcode-97.address=:10197/udp"
      # - "--entrypoints.xlxd-ambe-transcode-98.address=:10198/udp"
      # - "--entrypoints.xlxd-ambe-transcode-99.address=:10199/udp"
    ports:
      # The HTTP port
      - "0.0.0.0:80:80/tcp"
      # The Web UI (enabled by --api.insecure=true)
      - "0.0.0.0:8080:8080/tcp"
    networks:
      proxy:
        ipv4_address: "10.0.0.2"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/traefik/traefik.log:/var/log/traefik.log
      #- /opt/traefik/traefik.toml:/traefik.toml
    dns:
      - 1.1.1.1
    dns_search: kk7mnz.com
    restart: unless-stopped

  xlxd:
    image: mfiscus/xlxd:latest
    container_name: xlxd
    domainname: kk7mnz.com
    hostname: xlxd_container
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=docker_proxy"
      - "traefik.frontend=xlxd-frontend"
      - "traefik.frontend.rule=HostRegexp:xlx847.kk7mnz.com,{catchall:.*}"
      - "traefik.http.routers.xlxd-frontend.rule=Host(`xlx847.kk7mnz.com`)"
      - "traefik.http.routers.xlxd-frontend.entrypoints=www"
      - "traefik.http.services.xlxd-frontend.loadbalancer.server.port=8470"
    environment:
      CALLSIGN: 'KK7MNZ'
      EMAIL: 'matt@kk7mnz.com'
      # URL for dashboard
      URL: 'xlx847.kk7mnz.com'
      # Port to run dashboard on
      PORT: '8470'
      XRFNUM: 'XLX847'
      COUNTRY: 'United States'
      # Make your ysf reflector stand out in the list
      DESCRIPTION: 'Chandler Ham Radio Club'
      # Number of modules to run (default: 10, max: 26)
      MODULES: '4'
      # Support for labeling first 4 modules
      MODULEA: 'Main'
      MODULEB: 'TBD'
      MODULEC: 'TBD'
      MODULED: 'TBD'
      # Enable ysf auto linking (disable: 0, enable: 1)
      YSF_AUTOLINK_ENABLE: '1'
      # Define default module to auto link to
      YSF_AUTOLINK_MODULE: 'A'
      # I read somewhere that it was important to define this so I built in support. Not sure what it is for yet.
      YSF_DEFAULT_NODE_RX_FREQ: '438000000'
      YSF_DEFAULT_NODE_TX_FREQ: '438000000'
    networks:
      proxy:
        ipv4_address: "10.0.0.3"
    volumes:
      # volume for storing custom configuration files
      - /opt/xlxd:/config
    privileged: true
    devices:
      # grant access to AMBE USB DV vocodor (tested with ThumbDV)
      - /dev/usb:/dev/usb
    dns:
      - 1.1.1.1
    dns_search: kk7mnz.com
    restart: unless-stopped
    